version: '3'
services:
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.2
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
  kibana:
    image: docker.elastic.co/kibana/kibana:8.8.2
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://elastic:9200
      ELASTICSEARCH_HOSTS: http://elastic:9200
  logstash:
    image: docker.elastic.co/logstash/logstash:8.8.2
    ports:
      - 9000:9000
    volumes:
      - ./logstash-error-apache.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./grok-patterns:/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-patterns-core-4.1.2/patterns/grok-patterns
    depends_on:
      - elastic
