input {
  tcp {
    port  => 9000
    codec => line
  }
}

filter {
  # 1. Initial Parse (The Grok we built)
  grok {
    # 100.64.15.62 - - [06/May/2026:23:27:25 +0000] "GET /geonetwork/srv/api/records/0c66fd8f-4b54-450f-b336-c6a76569516c HTTP/1.1" 200 8440 84
    match => { "message" => "%{IPORHOST:client_ip}\s+%{NOTSPACE:ident}\s+%{NOTSPACE:auth}\s+\[%{HTTPDATE:timestamp}\]\s+\"%{WORD:method}\s+/(?<proxy_app>[^/?]+)%{NOTSPACE:request_uri}\s+HTTP/%{NUMBER:http_version}\"\s+%{NUMBER:status}\s+%{NUMBER:bytes_sent}\s+%{NUMBER:response_time_ms}"  }
  }
  # 2. Extract WMS Parameters (The KV Magic)
  # This targets the request_uri and splits it into fields like 'LAYERS' and 'FORMAT'
  if "/geoserver/ows" in [request_uri] {
    kv {
      source => "request_uri"
      field_split => "&?"
      target => "wms_params"
      include_keys => [ "LAYERS", "SERVICE", "REQUEST", "FORMAT", "BBOX", "SRS", "CRS" ]
    }
  }

  # 3. Clean up and Type Conversion
  mutate {
      convert => {
        "status" => "integer"
        "bytes_sent" => "integer"
        "response_time_ms" => "integer"
      }
    }

  date {
    match => [ "timestamp", "dd/MMM/yyyy:HH:mm:ss Z" ]
    target => "@timestamp"
  }
}


output {
  elasticsearch { hosts => ["elastic:9200"] }
  stdout { codec => rubydebug }
}
